name: Deploy Flask App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m venv venv
          venv/bin/pip install -r Brusak_Project/requirements.txt
      - name: Deploy to Render
        uses: actions/setup-python@v2
        with:
          github_token: ${{ secrets.BRUSAK_SECRET }}
          render_token: ${{ secrets.RENDER }}
          render_app_name: app
